<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="banner.local" name="com.exiu.tester.carowener.my.Test033_More" tests="1" failures="0" timestamp="05 七月 2017 08:15:11 GMT" time="45.997" errors="1">
  <testcase name="关于我们" time="45.997" classname="com.exiu.tester.carowener.my.Test033_More">
    <error type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : 拨打客服电话失败 expected [false] but found [true] in method : .关于我们(Test033_More:61)
	at com.exiu.tester.carowener.my.Test033_More.关于我们(Test033_More.java:61)
]]>
    </error>
  </testcase> <!-- 关于我们 -->
</testsuite> <!-- com.exiu.tester.carowener.my.Test033_More -->
